version: '3'
services:
  dbtest:
    image: microsoft/mssql-server-linux
    restart: always
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "WdUCJWOUYi484fZRyCUR"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
